window.CRETE_PRONUNCIATIONS = {
  'Heraklion': 'Ираклион',
  'Mochlos': 'Мохлос',
  'Sitia': 'Сития',
  'Lasithi': 'Ласити',
  'Mirabello Bay': 'залив Мирабелло',
  'Agios Nikolaos': 'Айос Николаос',
  'Pachia Ammos': 'Пахия Аммос',
  'Gournia': 'Гурния',
  'Toplou': 'Топлу',
  'Toplou Fabrica': 'Топлу Фабрика',
  'Paralia Chiona': 'Паралия Хиона',
  'Hiona Taverna': 'таверна Хиона',
  'Palekastro': 'Палекастро',
  'Itanos': 'Итанос',
  'Erimoupolis': 'Эримуполис',
  'Vai Beach': 'пляж Ваи',
  'Ziros': 'Зирос',
  'Xerokampos': 'Ксерокамбос',
  'Mazida Ammos': 'Мазида Аммос',
  'Zakros': 'Закрос',
  'Kato Zakros': 'Като Закрос',
  'Kazarma Fortress': 'крепость Казарма',
  'Lastros': 'Ластрос',
  'Mathena Olive Tree': 'оливковое дерево Матена',
  'Pomegranate Garden Villa': 'Помегранат Гарден Вилла',
  'Platanes': 'Платанес',
  'Rethymno': 'Ретимно',
  'Vitsentzos Kornaros': 'Вицендзос Корнарос',
  "Panigiri": "панигири",
  "Fortezza": "Фортецца",
  "Rimondi Fountain": "фонтан Римонди",
  "Venetian Loggia": "Венецианская Лоджия",
  "Caretta caretta": "каретта каретта",
  "ARCHELON": "Архелон",
  "Amari Valley": "долина Амари",
  "Amari": "Амари",
  "Psiloritis": "Псилоритис",
  "Mount Kedros": "гора Кедрос",
  "Kedros": "Кедрос",
  "Platis River": "река Платис",
  "Fabrika": "Фабрика",
  "kafeneio": "кафенио",
  "Mount Samitos": "гора Самитос",
  "Samitos": "Самитос",
  "Agia Anna": "Айя Анна",
  "Panagia Kera": "Панагия Кера",
  "Kallergis": "Каллергис",
  "Agios Georgios": "Айос Георгиос",
  "Monastiraki": "Монастираки",
  "Meronas": "Меронас",
  "Panagia": "Панагия",
  "Elenes": "Эленес",
  "Gerakari": "Геракари",
  "Organic Farmers’ Market": "органик фармерс маркет",
  "Koumoundourou Street": "улица Кумундуроу",
  "Akrotiri": "Акротири",
  "White Mountains": "Белые горы",
  "Cretan Sea": "Критское море",
  "Souda Bay": "бухта Суда",
  "Stavros": "Ставрос",
  "Zorba the Greek": "Грек Зорба",
  "Anthony Quinn": "Энтони Куинн",
  "Michael Cacoyannis": "Михалис Какояннис",
  "Nikos Kazantzakis": "Никос Казандзакис",
  "Kouzina EPE": "Кузина Э П Э",
  "Splantzia": "Спландзья",
  "mageirio": "магирио",
  "Marathi": "Марати",
  "Laiki": "Лаики",
  "Eleutherna": "Элефтерна",
  "Orthi Petra": "Орти Петра",
  "Panormo": "Панормо",
  "meltemi": "мельтеми",
  "Korakas": "Коракас",
  "Fodele": "Фоделе",
  "Domenikos Theotokopoulos": "Доменикос Теотокопулос",
  "El Greco": "Эль Греко",
  "Candia": "Кандия",
  "Venice": "Венеция",
  "Rome": "Рим",
  "Toledo": "Толедо",
  "Litinos": "Литинос",
  "antikristo": "антикристо",
  "tsigariasto": "цигарьясто",
  "gamopilafo": "гамопилафо",
  "Wednesday": "среда",
  "Thursday": "четверг",
  "Old Town": "старый город",
  "Municipal Garden": "муниципальный сад",
  "Homemade Food": "домашняя еда",
  "cooked dishes": "готовые блюда",
  "stuffed vegetables": "фаршированные овощи",
  "greens": "зелень",
  "souvlaki": "сувлаки",
  "moussaka": "мусака",
  "carbonara": "карбонара",
  "stew": "тушёное блюдо",
  "meze": "мезе",
  "raki": "раки",
  "Apostoloi": "Апостоли",
  "Nefs Amari": "Нефс Амари",
  "Opsigias": "Опсигьяс",
  "Agia Sophia": "Айя София",
  "Chania": "Ханья",
  "Crete": "Крит",
  "UNESCO": "ЮНЕСКО",
  "Museum of Ancient Eleutherna": "музей древней Элефтерны",
  "Homer in Crete": "Гомер на Крите"
};
