window.CRETE_PRONUNCIATIONS = {
  'Heraklion': 'Ираклион',
  'Mochlos': 'Мохлос',
  'Sitia': 'Сития',
  'Lasithi': 'Ласити',
  'Mirabello Bay': 'залив Мирабелло',
  'Agios Nikolaos': 'Айос Николаос',
  'Pachia Ammos': 'Пахия Аммос',
  'Gournia': 'Гурния',
  'Toplou': 'Топлу',
  'Toplou Fabrica': 'Топлу Фабрика',
  'Paralia Chiona': 'Паралия Хиона',
  'Hiona Taverna': 'таверна Хиона',
  'Palekastro': 'Палекастро',
  'Itanos': 'Итанос',
  'Erimoupolis': 'Эримуполис',
  'Vai Beach': 'пляж Ваи',
  'Ziros': 'Зирос',
  'Xerokampos': 'Ксерокамбос',
  'Mazida Ammos': 'Мазида Аммос',
  'Zakros': 'Закрос',
  'Kato Zakros': 'Като Закрос',
  'Kazarma Fortress': 'крепость Казарма',
  'Lastros': 'Ластрос',
  'Mathena Olive Tree': 'оливковое дерево Матена',
  'Pomegranate Garden Villa': 'Помегранат Гарден Вилла',
  'Platanes': 'Платанес',
  'Rethymno': 'Ретимно',
  'Vitsentzos Kornaros': 'Вицендзос Корнарос',
  "Panigiri": "панигири",
  "Fortezza": "Фортецца",
  "Rimondi Fountain": "фонтан Римонди",
  "Venetian Loggia": "Венецианская Лоджия",
  "Caretta caretta": "каретта каретта",
  "ARCHELON": "Архелон",
  "Amari Valley": "долина Амари",
  "Amari": "Амари",
  "Psiloritis": "Псилоритис",
  "Mount Kedros": "гора Кедрос",
  "Kedros": "Кедрос",
  "Platis River": "река Платис",
  "Fabrika": "Фабрика",
  "kafeneio": "кафенио",
  "Mount Samitos": "гора Самитос",
  "Samitos": "Самитос",
  "Agia Anna": "Айя Анна",
  "Panagia Kera": "Панагия Кера",
  "Kallergis": "Каллергис",
  "Agios Georgios": "Айос Георгиос",
  "Monastiraki": "Монастираки",
  "Meronas": "Меронас",
  "Panagia": "Панагия",
  "Elenes": "Эленес",
  "Gerakari": "Геракари",
  "Organic Farmers’ Market": "органик фармерс маркет",
  "Koumoundourou Street": "улица Кумундуроу",
  "Akrotiri": "Акротири",
  "White Mountains": "Белые горы",
  "Cretan Sea": "Критское море",
  "Souda Bay": "бухта Суда",
  "Stavros": "Ставрос",
  "Zorba the Greek": "Грек Зорба",
  "Anthony Quinn": "Энтони Куинн",
  "Michael Cacoyannis": "Михалис Какояннис",
  "Nikos Kazantzakis": "Никос Казандзакис",
  "Kouzina EPE": "Кузина Э П Э",
  "Splantzia": "Спландзья",
  "mageirio": "магирио",
  "Marathi": "Марати",
  "Laiki": "Лаики",
  "Eleutherna": "Элефтерна",
  "Orthi Petra": "Орти Петра",
  "Panormo": "Панормо",
  "meltemi": "мельтеми",
  "Korakas": "Коракас",
  "Fodele": "Фоделе",
  "Domenikos Theotokopoulos": "Доменикос Теотокопулос",
  "El Greco": "Эль Греко",
  "Candia": "Кандия",
  "Venice": "Венеция",
  "Rome": "Рим",
  "Toledo": "Толедо",
  "Litinos": "Литинос",
  "antikristo": "антикристо",
  "tsigariasto": "цигарьясто",
  "gamopilafo": "гамопилафо",
  "Wednesday": "среда",
  "Thursday": "четверг",
  "Old Town": "старый город",
  "Municipal Garden": "муниципальный сад",
  "Homemade Food": "домашняя еда",
  "cooked dishes": "готовые блюда",
  "stuffed vegetables": "фаршированные овощи",
  "greens": "зелень",
  "souvlaki": "сувлаки",
  "moussaka": "мусака",
  "carbonara": "карбонара",
  "stew": "тушёное блюдо",
  "meze": "мезе",
  "raki": "раки",
  "Apostoloi": "Апостоли",
  "Nefs Amari": "Нефс Амари",
  "Opsigias": "Опсигьяс",
  "Agia Sophia": "Айя София",
  "Chania": "Ханья",
  "Crete": "Крит",
  "UNESCO": "ЮНЕСКО",
  "Museum of Ancient Eleutherna": "музей древней Элефтерны",
  "Homer in Crete": "Гомер на Крите"
};

window.CRETE_PHONEMES = {
  'храмовым': 'ˈxra.mə.vɨm',
  'храмовом': 'ˈxra.mə.vəm',
  'маскаронов': 'mə.skɐ.ˈro.nəf',
  'некрополь': 'nʲɪ.ˈkro.pəlʲ',
  'протодворцовому': 'pro.tə.dvɐr.ˈt͡so.və.mu',
  'раннехристианской': 'ranʲ.nʲɪ.xrʲɪsʲ.tʲɪ.ˈan.skəj',
  'раки': 'ra.ˈkʲi',
  'мезе': 'mʲe.ˈzʲe',
  'сувлаки': 'su.ˈvla.kʲi',
  'мусака': 'mu.sa.ˈka',
  'мусаки': 'mu.sa.ˈkʲi',
  'карбонары': 'kar.bo.ˈna.rɨ',
  'кафенио': 'kɐ.fʲɪ.ˈnʲi.o',
  'панигири': 'pɐ.nʲɪ.ˈɡʲi.rʲɪ',
  'Лаики': 'la.i.ˈkʲi',
  'Ираклион': 'i.ˈra.klʲi.on',
  'Сития': 'sʲɪ.ˈtʲi.jə',
  'Мохлос': 'ˈmox.los',
  'Мирабелло': 'mʲi.ra.ˈbʲel.lo',
  'Агиос': 'ˈa.gʲi.os',
  'Айос': 'ˈa.jos',
  'Айя': 'ˈa.ja',
  'Николаос': 'nʲi.ˈko.la.os',
  'Георгиос': 'ɡʲɪ.ˈor.ɡʲi.os',
  'Гурния': 'gur.ˈnʲi.ja',
  'Гурнией': 'gur.ˈnʲi.jəj',
  'Топлу': 'to.ˈplu',
  'Хиона': 'xʲi.ˈo.na',
  'Палекастро': 'pa.ˈlʲe.ka.stro',
  'Итанос': 'ˈi.ta.nos',
  'Эримуполис': 'e.rʲi.ˈmu.po.lʲis',
  'Зирос': 'ˈzʲi.ros',
  'Ксерокамбос': 'kse.ˈro.kam.bos',
  'Закрос': 'ˈza.kros',
  'Казарма': 'kɐ.ˈzar.ma',
  'Ластрос': 'ˈla.stros',
  'Вицендзос': 'vʲi.ˈt͡sen.dzos',
  'Корнарос': 'kor.ˈna.ros',
  'Платанес': 'pla.ta.ˈnʲes',
  'Платанеса': 'pla.ta.ˈnʲe.sa',
  'Платанесе': 'pla.ta.ˈnʲe.sʲe',
  'Ретимно': 'ˈrʲe.tʲim.no',
  'Фортецца': 'for.ˈtʲet.t͡sa',
  'Римонди': 'rʲi.ˈmon.dʲi',
  'АРХЕЛОН': 'ar.xʲɪ.ˈlon',
  'каретта': 'ka.ˈrʲet.ta',
  'Амари': 'a.ˈma.rʲi',
  'Псилоритис': 'psʲɪ.lɐ.ˈrʲi.tʲɪs',
  'Псилоритиса': 'psʲɪ.lɐ.ˈrʲi.tʲɪ.sə',
  'Псилоритисом': 'psʲɪ.lɐ.ˈrʲi.tʲɪ.səm',
  'Кедрос': 'ˈkʲe.dros',
  'Кедроса': 'ˈkʲe.dro.sa',
  'Кедросом': 'ˈkʲe.dro.səm',
  'Платис': 'pla.ˈtʲis',
  'Апостоли': 'a.ˈpo.sto.lʲi',
  'Самитос': 'ˈsa.mʲi.tos',
  'Панагия': 'pɐ.nɐ.ˈɡʲi.jə',
  'Каллергис': 'ka.ˈlʲer.gʲis',
  'Опсигьяс': 'ɐp.sʲɪ.ˈɡʲjas',
  'Монастираки': 'mə.nɐ.stʲɪ.ˈra.kʲɪ',
  'Меронас': 'ˈmʲe.ro.nas',
  'Меронаса': 'ˈmʲe.ro.na.sa',
  'Эленес': 'e.ˈlʲe.nʲes',
  'Геракари': 'ɡʲɪ.rɐ.ˈka.rʲɪ',
  'Акротири': 'ɐ.krɐ.ˈtʲi.rʲɪ',
  'Ханья': 'xa.ˈnʲja',
  'Ханьи': 'xa.ˈnʲjɪ',
  'Ханье': 'xa.ˈnʲjɪ',
  'Ханьей': 'xa.ˈnʲjəj',
  'Суда': 'ˈsu.da',
  'Судой': 'ˈsu.doj',
  'Ставрос': 'sta.ˈvros',
  'Ставроса': 'sta.ˈvro.sa',
  'Какояннис': 'ka.ko.ˈjan.nʲis',
  'Казандзакис': 'kɐ.zɐn.ˈd͡za.kʲɪs',
  'Казандзакиса': 'kɐ.zɐn.ˈd͡za.kʲɪ.sə',
  'Спландзья': 'ˈsplan.dzʲja',
  'магирио': 'mɐ.ɡʲɪ.ˈrʲi.o',
  'Марати': 'ma.ˈra.tʲi',
  'Элефтерна': 'e.ˈlʲef.tʲer.na',
  'Элефтерны': 'e.ˈlʲef.tʲer.nɨ',
  'Элефтерне': 'e.ˈlʲef.tʲer.nʲe',
  'Орти': 'or.ˈtʲi',
  'Петра': 'ˈpʲe.tra',
  'Панормо': 'ˈpa.nor.mo',
  'мельтеми': 'mʲel.ˈtʲe.mʲi',
  'Коракас': 'ˈko.ra.kas',
  'Фоделе': 'ˈfo.dʲe.lʲe',
  'Малевизи': 'mɐ.lʲɪ.ˈvʲi.zʲɪ',
  'Теотокопулос': 'tʲɪ.ɐ.tɐ.ˈko.pu.ləs',
  'Теотокопулоса': 'tʲɪ.ɐ.tɐ.ˈko.pu.lə.sə',
  'Кандия': 'ˈkan.dʲi.ja',
  'Кандии': 'ˈkan.dʲi.i',
  'Кандию': 'ˈkan.dʲi.ju',
  'Греко': 'ˈgrʲe.ko',
  'Литинос': 'ˈlʲi.tʲi.nos',
  'антикристо': 'ɐn.tʲɪ.krʲɪ.ˈsto',
  'цигарьясто': 't͡sɨ.ɡɐ.rʲjɐ.ˈsto',
  'гамопилафо': 'ɡɐ.mɐ.ˈpʲi.lɐ.fə'
};
