window.CRETE_PRONUNCIATIONS = {
  'Heraklion': 'Ираклион',
  'Mochlos': 'Мохлос',
  'Sitia': 'Сития',
  'Lasithi': 'Ласити',
  'Mirabello Bay': 'залив Мирабелло',
  'Agios Nikolaos': 'Айос Николаос',
  'Pachia Ammos': 'Пахия Аммос',
  'Gournia': 'Гурния',
  'Toplou': 'Топлу',
  'Toplou Fabrica': 'Топлу Фабрика',
  'Paralia Chiona': 'Паралия Хиона',
  'Hiona Taverna': 'таверна Хиона',
  'Palekastro': 'Палекастро',
  'Itanos': 'Итанос',
  'Erimoupolis': 'Эримуполис',
  'Vai Beach': 'пляж Ваи',
  'Ziros': 'Зирос',
  'Xerokampos': 'Ксерокамбос',
  'Mazida Ammos': 'Мазида Аммос',
  'Zakros': 'Закрос',
  'Kato Zakros': 'Като Закрос',
  'Kazarma Fortress': 'крепость Казарма',
  'Lastros': 'Ластрос',
  'Mathena Olive Tree': 'оливковое дерево Матена',
  'Pomegranate Garden Villa': 'Помегранат Гарден Вилла',
  'Platanes': 'Платанес',
  'Rethymno': 'Ретимно',
  'Vitsentzos Kornaros': 'Вицендзос Корнарос'
};
